spring.application.name=padel-backend

# Base de données H2 in-memory
spring.datasource.url=jdbc:h2:mem:padeldb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Console H2 (pour voir la BD dans le navigateur)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.h2.console.settings.web-allow-others=false
spring.jpa.open-in-view=false

